version: '3.5'

services:
  docker-testing-app-web:
    container_name: docker-testing-app-web
    build:
      context: ./docker/nginx
      args:
        UID: $U_ID
    ports:
      - 1000:80
    volumes:
      - ./public:/appdata/www/public
    depends_on:
      - docker-testing-app-be
    networks:
      - docker-testing-app-network

  docker-testing-app-be:
    container_name: docker-testing-app-be
    build:
      context: docker/php
      args:
        UID: $U_ID
    volumes:
      - ./:/appdata/www
    ###> XDEBUG 3 ###
    # Use your client IP here
    # Linux: run "ip a | grep docker0"
    # Windows (with WSL2) and Mac: host.docker.internal
    environment:
      XDEBUG_CLIENT_HOST: 172.17.0.1
      XDEBUG_CLIENT_PORT: 9003
      PHP_IDE_CONFIG: serverName=docker-testing-app
    networks:
      - docker-testing-app-network

  docker-testing-app-db:
    container_name: docker-testing-app-db
    restart: always
    hostname: myhost
    build:
      context: ./docker/database
    ports:
      - 9091:5432
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - docker-testing-app-db-data:/var/lib/postgresql/data
    networks:
      - docker-testing-app-network

volumes:
  docker-testing-app-db-data:

networks:
  docker-testing-app-network:
    external: true
